port: 3333
socks-port: 23456
redir-port: 23457
allow-lan: true
mode: Rule
log-level: error
experimental:
  ignore-resolve-fail: true
secret: "clash"
profile:
  store-selected: true
ipv6: false
config-name: config-generated

#dns:
#  enable: true
#  listen: :53
#  enhanced-mode: redir-host
#  nameserver:
#    - 114.114.114.114
#    - 223.5.5.5
#  fallback:
#    - 8.8.8.8
