const fs = require('fs-extra');
const yaml = require('js-yaml');
const path = require('path');
const url = require('url');

const {PROXIES_DIR} = require('../paths');
const {stringToSafeFilename} = require('../utils/string');
const {decodeSSRUri} = require('../proxy/ssr');
const {decodeSSUri} = require('../proxy/ss');
const {decodeVmessUri} = require('../proxy/vmess');

/**
 * Decode base64 string.
 * @param str
 * @returns {string}
 */
const decodeBase64String = (str) => {
  return Buffer.from(str, 'base64').toString();
}

/**
 * Alert that the proxy file already exists.
 * @param proxyFilePath
 */
const alertExists = (proxyFilePath) => {
  console.error('Failed: Proxy file already exists at', proxyFilePath);
  console.log('Create a proxy with a assigned name: clash add-proxy <uri> [name]');
}

/**
 * Add a ss proxy.
 * @param uri
 * @returns {Promise<void>}
 */
const addSSProxy = async (uri) => {
  const [, , , , proxy_name] = process.argv;
  const proxy = decodeSSUri(uri, proxy_name);
  const proxyFilePath = path.resolve(PROXIES_DIR, `${stringToSafeFilename(proxy.name)}.yaml`);
  if (fs.pathExistsSync(proxyFilePath)) {
    return alertExists(proxyFilePath);
  }
  let yml = yaml.dump(proxy, {indent: 2});
  await fs.outputFile(proxyFilePath, yml);
  // console.log(yml);
  console.log('Proxy file generated at', proxyFilePath);
};

/**
 * Add a ssr proxy.
 * this function was generated by GitHub Copilot, I didn't test it. Use it at your own risk.
 * @param uri
 * @returns {Promise<void>}
 */
const addSSRProxy = async (uri) => {
  const [, , , , proxy_name] = process.argv;
  const proxy = decodeSSRUri(uri, proxy_name);
  const proxyFilePath = path.resolve(PROXIES_DIR, `${stringToSafeFilename(proxy.name)}.yaml`);
  if (fs.pathExistsSync(proxyFilePath)) {
    return alertExists(proxyFilePath);
  }
  const yml = yaml.dump(proxy, {indent: 2});
  await fs.outputFile(proxyFilePath, yml);
  console.log(yml);
  console.log('Proxy file generated at', proxyFilePath);
}


/**
 * Add a vmess proxy.
 * @param uri
 * @returns {Promise<void>}
 */
const addVmessProxy = async (uri) => {
  const [, , , , proxy_name] = process.argv;
  const proxy = decodeVmessUri(uri, proxy_name);
  const proxyFilePath = path.resolve(PROXIES_DIR, `${stringToSafeFilename(proxy.name)}.yaml`);
  if (fs.pathExistsSync(proxyFilePath)) {
    return alertExists(proxyFilePath);
  }
  const yml = yaml.dump(proxy, {indent: 2});
  await fs.outputFile(proxyFilePath, yml);
  // console.log(yml);
  console.log('Proxy file generated at', proxyFilePath);
}

const addProxy = async () => {
  const [, , , uri] = process.argv;

  if (!uri) {
    console.log('No URI provided');
    return;
  }

  const {protocol} = url.parse(uri);

  switch (protocol) {
    case 'ss:':
      await addSSProxy(uri);
      break;
    case 'ssr:':
      await addSSRProxy(uri);
      break;
    case 'vmess:':
      await addVmessProxy(uri);
      break;
    default:
      console.log('Unsupported protocol', protocol);
  }

}

module.exports = addProxy;
